version: '3.8'

services:
  box-bot:
    image: twobrowin/box-bot:1.1.13
    build:
     context: .
    ports:
      # - 8080:8080
      - 5432:5432
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - 8180:8180
    command: start-dev --http-port=8180 --import-realm --verbose
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd