'yes': –î–∞
'no':  –ù–µ—Ç
none:  –ü—É—Å—Ç–æ

there_was_en_error: –ü—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞!

logout: –í—ã–π—Ç–∏

done:  –í—ã–ø–æ–ª–Ω–µ–Ω–æ
super: –°—É–ø–µ—Ä

is_active:    –†–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—è –∞–∫—Ç–∏–≤–Ω–∞
is_inactive:  –†–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—è –Ω–µ –∞–∫—Ç–∏–≤–Ω–∞
set_inactive: –û—Ç–º–µ–Ω–∏—Ç—å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—é
set_active:   –í–µ—Ä–Ω—É—Ç—å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—é

has_been_set_inactive: –†–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—è –¥–µ–∞–∫—Ç–∏–≤–∏—Ä–æ–≤–∞–Ω–∞
has_been_set_active:   –†–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—è –∞–∫—Ç–∏–≤–∏—Ä–æ–≤–∞–Ω–∞

data_empty: –ù–µ –∑–∞–ø–æ–ª–Ω–µ–Ω–æ
register:   –£–ø—Ä–∞–≤–ª–µ–Ω–∏–µ —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–µ–π

switch:        –†—É–±–∏–ª—å–Ω–∏–∫
groups:        –ì—Ä—É–ø–ø—ã
users:         –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–∏
registration:  –ü–∞—Ä–∞–º–µ—Ç—Ä—ã —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏
report:        –û—Ç—á–µ—Ç
notifications: –û–ø–æ–≤–µ—â–µ–Ω–∏—è
keyboard:      –ö–ª–∞–≤–∏–∞—Ç—É—Ä–∞
settings:      –ù–∞—Å—Ç—Ä–æ–π–∫–∏
logs:          –õ–æ–≥–∏

timestamp: –ú–µ—Ç–∫–∞ –≤—Ä–µ–º–µ–Ω–∏
message:   –°–æ–æ–±—â–µ–Ω–∏–µ

key:         –ö–ª—é—á
description: –û–ø–∏—Å–∞–Ω–∏–µ
value:       –ó–Ω–∞—á–µ–Ω–∏–µ

bot_status: –°—Ç–∞—Ç—É—Å –±–æ—Ç–∞

on_male:         –í–∫–ª—é—á—ë–Ω
off_male:        –í—ã–∫–ª—é—á—ë–Ω
restart_planned: –ù–∞–∑–Ω–∞—á–µ–Ω –ø–µ—Ä–µ–∑–∞–ø—É—Å–∫
restarting:      –ü–µ—Ä–µ–∑–∞–ø—É—Å–∫–∞–µ—Ç—Å—è
service_mode:    –°–µ—Ä–≤–∏—Å–Ω—ã–π —Ä–µ–∂–∏–º

turn_on:         –í–∫–ª—é—á–∏—Ç—å
turn_off:        –í—ã–∫–ª—é—á–∏—Ç—å
restart_normal:  –ü–µ—Ä–µ–∑–∞–ø—É—Å—Ç–∏—Ç—å –≤ –Ω–æ—Ä–º–∞–ª—å–Ω—ã–π —Ä–µ–∂–∏–º
restart_service: –ü–µ—Ä–µ–∑–∞–ø—É—Å—Ç–∏—Ç—å –≤ —Å–µ—Ä–≤–∏—Å–Ω—ã–π —Ä–µ–∂–∏–º

is_registration_open: –°—Ç–∞—Ç—É—Å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏

registration_opened: –û—Ç–∫—Ä—ã—Ç–∞
registration_closed: –ó–∞–∫—Ä—ã—Ç–∞

registration_close: –ó–∞–∫—Ä—ã—Ç—å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—é
registration_open:  –û—Ç–∫—Ä—ã—Ç—å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏—é

username: –ò–º—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –¢–µ–ª–µ–≥—Ä–∞–º

chat_id:     Id —á–∞—Ç–∞
status:      –°—Ç–∞—Ç—É—Å
description: –û–ø–∏—Å–∞–Ω–∏–µ

group_inactive:     –ù–µ –∞–∫—Ç–∏–≤–Ω–∞
group_normal:       –û–±—ã—á–Ω–∞—è
group_admin:        –ê–¥–º–∏–Ω—ã
group_super_admin:  –°—É–ø–µ—Ä –∞–¥–º–∏–Ω—ã
group_news_channel: –ù–æ–≤–æ—Å—Ç–Ω–æ–π –∫–∞–Ω–∞–ª

keyboard_keys: –ö–ª–∞–≤–∏–∞—Ç—É—Ä–∞

reply_condition_message_id: –°–æ–æ–±—â–µ–Ω–∏–µ

text_markdown: –¢–µ—Å—Ç —Ä–∞–∑–º–µ—Ç–∫–∏ markdwon
photo_link:    –°—Å—ã–ª–∫–∞ –Ω–∞ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–µ

keyboard_key_inactive: –ù–µ –∞–∫—Ç–∏–≤–Ω–∞
keyboard_key_normal:   –û–±—ã—á–Ω–∞—è –∫–Ω–æ–ø–∫–∞
keyboard_key_deferred: –û—Ç–ª–æ–∂–µ–Ω–Ω—ã–µ –≤–æ–ø—Ä–æ—Å—ã
keyboard_key_me:       –ü—Ä–æ—Ñ–∏–ª—å

keyboard_key_qr:   QR –∫–æ–¥
keyboard_key_news: –ù–æ–≤–æ—Å—Ç–∏
keyboard_key_back: –í–µ—Ä–Ω—É—Ç—å—Å—è –∫ –º–µ–Ω—é –≤—ã—à–µ
keyboard_key_me_change: –ò–∑–º–µ–Ω–µ–Ω–∏–µ –ø—Ä–æ—Ñ–∏–ª—è
keyboard_key_promocodes: –ü—Ä–æ–º–æ–∫–æ–¥—ã

field_branches: –í–µ—Ç–∫–∏ –ø–æ–ª–µ–π
fields: –ü–æ–ª—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π

is_ui_editable:  –ú–æ–∂–Ω–æ –º–µ–Ω—è—Ç—å –≤ UI
is_bot_editable: –ú–æ–∂–Ω–æ –º–µ–Ω—è—Ç—å –≤ –±–æ—Ç–µ
is_deferrable:   –ú–æ–∂–Ω–æ –æ—Ç–ª–æ–∂–∏—Ç—å
next_branch_id:  –°–ª–µ–¥—É—é—â–∞—è –≤–µ—Ç–∫–∞

field_branch_inactive: –ù–µ –∞–∫—Ç–∏–≤–Ω–∞
field_branch_normal:   –ê–∫—Ç–∏–≤–Ω–∞

order_place:       –ü–æ—Ä—è–¥–æ–∫
branch_id:         –í–µ—Ç–∫–∞
question_markdown: –í–æ–ø—Ä–æ—Å Markdown
answer_options:    –í–∞—Ä–∏–∞–Ω—Ç—ã –æ—Ç–≤–µ—Ç–∞
image_bucket:      –ë–∞–∫–µ—Ç –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–π
document_bucket:   –ë–∞–∫–µ—Ç –¥–æ–∫—É–º–µ–Ω—Ç–∞
is_boolean:        –ë—É–ª–µ–≤–æ

field_inactive: –ù–µ –∞–∫—Ç–∏–≤–µ–Ω
field_normal:   –ê–∫—Ç–∏–≤–µ–Ω
field_personal_notifiation: –° —É–≤–µ–¥–æ–º–ª–µ–Ω–∏–µ–º –æ –∑–Ω–∞—á–µ–Ω–∏–∏
field_jinja2_from_user_on_create: –í—ã—á–∏—Å–ª—è–µ–º–æ–µ Jinja2 –ø—Ä–∏ —Å–æ–∑–¥–∞–Ω–∏–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è

image:    –ò–∑–æ–±—Ä–∞–∂–µ–Ω–∏–µ
document: –î–æ–∫—É–º–µ–Ω—Ç

download_users_report: –í—ã–≥—Ä—É–∑–∫–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π

replyable_condition_messages: –°–æ–æ–±—â–µ–Ω–∏—è —Å —É—Å–ª–æ–≤–∏—è–º–∏ –∏ –æ—Ç–≤–µ—Ç–∞–º–∏
reply_condition_message_name: –û–±–æ–∑–Ω–∞—á–µ–Ω–∏–µ

condition_bool_field_id: –£—Å–ª–æ–≤–∏–µ –ø–æ–∫–∞–∑–∞/–æ—Ç–ø—Ä–∞–≤–∫–∏

reply_condition_bool_field_id: –£—Å–ª–æ–≤–∏–µ –æ—Ç–≤–µ—Ç–∞

reply_type: –¢–∏–ø –æ—Ç–≤–µ—Ç–∞
reply_type_branch_start:     –í–µ—Ç–∫–∞ –≤–æ–ø—Ä–æ—Å–æ–≤
reply_type_full_text_answer: –û–¥–∏–Ω –≤–æ–ø—Ä–æ—Å
reply_type_fast_answer:      –ë—ã—Å—Ç—Ä—ã–π –æ—Ç–≤–µ—Ç

reply_answer_field_id:        –í–æ–ø—Ä–æ—Å
reply_answer_field_branch_id: –í–µ—Ç–∫–∞ –≤–æ–ø—Ä–æ—Å–æ–≤
reply_keyboard_keys:          –ö–ª–∞–≤–∏—à–∏
reply_status_replies:         –û—Ç–≤–µ—Ç—ã

notifications: –£–≤–µ–¥–æ–º–ª–µ–Ω–∏—è
notify_date:   –î–∞—Ç–∞ —É–≤–µ–¥–æ–º–ª–µ–Ω–∏—è

notification_inactive:   –ù–µ –∞–∫—Ç–∏–≤–Ω–æ
notification_to_deliver: –û—Ç–ø—Ä–∞–≤–∏—Ç—å
notification_planned:    –ó–∞–ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–æ
notification_delivered:  –û—Ç–ø—Ä–∞–≤–ª–µ–Ω–æ

defer:   –û—Ç–ª–æ–∂–∏—Ç—å –∑–∞–ø–æ–ª–Ω–µ–Ω–∏–µ –Ω–∞ —ç—Ç–æ–º –≤–æ–ø—Ä–æ—Å–µ
defered: –ó–∞–ø–æ–ª–Ω–µ–Ω–∏–µ –æ—Ç–ª–æ–∂–µ–Ω–æ –Ω–∞ —ç—Ç–æ–º –≤–æ–ø—Ä–æ—Å–µ

download_file: –°–∫–∞—á–∞—Ç—å

parent_key_id: –†–æ–¥–∏—Ç–µ–ª—å—Å–∫–∞—è –∫–Ω–æ–ø–∫–∞

change: –ò–∑–º–µ–Ω–∏—Ç—å
append: –î–æ–±–∞–≤–∏—Ç—å

personal_notification_inactive: üì¥ –ù–µ –∞–∫—Ç–∏–≤–Ω–æ
personal_notification_to_deliver: üì≤ –ó–∞–ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–∞ –¥–æ—Å—Ç–∞–≤–∫–∞
personal_notification_delivered: ‚úÖ –î–æ—Å—Ç–∞–≤–ª–µ–Ω–æ

promocodes: –ü—Ä–æ–º–æ–∫–æ–¥—ã

promocode_active:   –ê–∫—Ç–∏–≤–µ–Ω
promocode_expired:  –ü—Ä–æ—Å—Ä–æ—á–µ–Ω
promocode_inactive: –ù–µ –∞–∫—Ç–∏–≤–µ–Ω

source:      –ò—Å—Ç–æ—á–Ω–∏–∫
value:       –ö–æ–¥ –ø—Ä–æ–º–æ–∫–æ–¥–∞
description: –û–ø–∏—Å–∞–Ω–∏–µ
expire_at:   –î–∞—Ç–∞ –æ–∫–æ–Ω—á–∞–Ω–∏—è –¥–µ–π—Å—Ç–≤–∏—è

validation_regexp: –†–µ–≥—É–ª—è—Ä–Ω–æ–µ –≤—ã—Ä–∞–∂–µ–Ω–∏–µ –≤–∞–ª–∏–¥–∞—Ü–∏–∏
validation_error_markdown: –û—à–∏–±–∫–∞ Markdown
validation_remove_regexp: –†–µ–≥—É–ª—è—Ä–Ω–æ–µ –≤—ã—Ä–∞–∂–µ–Ω–∏–µ —É–¥–∞–ª–µ–Ω–∏—è
is_skippable: –ú–æ–∂–Ω–æ –ø—Ä–æ–ø—É—Å—Ç–∏—Ç—å

cancel: ‚ùå –û—Ç–º–µ–Ω–∞
skip:   ‚è≠ –ü—Ä–æ–ø—É—Å—Ç–∏—Ç—å
change_canceled: –ò–∑–º–µ–Ω–µ–Ω–∏–µ –æ—Ç–º–µ–Ω–µ–Ω–æ

submit_qr:  üìù –ó–∞—è–≤–∫–∞ –Ω–∞ –ø—Ä–æ–ø—É—Å–∫
confirm_qr: ‚úÖ –ü–æ–¥—Ç–≤–µ—Ä–¥–∏—Ç—å –∑–∞—è–≤–∫—É
qr_canceled: –û—Ç–ø—Ä–∞–≤–∫–∞ –∑–∞—è–≤–∫–∏ –æ—Ç–º–µ–Ω–µ–Ω–∞

download_submited: üì• –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–∏, –ø–æ–¥–∞–≤—à–∏–µ –∑–∞—è–≤–∫—É –Ω–∞ qr
send_approved:     üì§ –ó–∞–≥—Ä—É–∑–∏—Ç—å —Ç–∞–±–ª–∏—Ü—É qr –∫–æ–¥–æ–≤

submitted_empty: –ù–µ—Ç –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π, –ø–æ–¥–∞–≤—à–∏—Ö –∑–∞—è–≤–∫—É –Ω–∞ qr –∫–æ–¥
send_approved_to_send:  –û—Ç–ø—Ä–∞–≤—å—Ç–µ —Ñ–∞–π–ª, —Å–æ–¥–µ—Ä–∂–∞—â–∏–π —Ç–∞–±–ª–∏—Ü—É –ø–æ–¥—Ç–≤–µ—Ä–∂–¥—ë–Ω–Ω—ã—Ö qr –∫–æ–¥–æ–≤
send_approved_canceled: –û—Ç–ø—Ä–∞–≤–∫–∞ —Ñ–∞–π–ª–∞ –æ—Ç–º–µ–Ω–µ–Ω–∞
send_approved_done:     "Qr –∫–æ–¥—ã –≤—ã–¥–∞–Ω—ã –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è–º:"
